# This is a linux-msft-wsl workflow to build wsl linux kernel
name: Build wsl linux kernel

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: rameshmarisa/wsl-kernel:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build wsl linux kernel
        run: |
          make -j2 KCONFIG_CONFIG=Microsoft/config-wsl 
          
      - name: artifact bzImage
        uses: actions/upload-artifact@v2
        with:
          name: bzImage
          path: |
            src/arch/x86/boot/bzImage
