# This is a linux-msft-wsl workflow to build wsl linux kernel
name: Build wsl linux kernel

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build -t wsl_kernel:latest - < Dockerfile

      - name: Build wsl linux kernel
        run: |
          mkdir -p output
          docker run -v ${{ github.workspace }}/output:/src/arch/x86/boot wsl_kernel:latest make KCONFIG_CONFIG=Microsoft/config-wsl

      - name: artifact bzImage
        uses: actions/upload-artifact@v2
        with:
          path: |
            output/bzImage
